# Generated by Django 5.2.8 on 2025-11-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_ID', models.IntegerField()),
                ('Brand', models.CharField(max_length=1)),
                ('Quality', models.CharField(max_length=10)),
                ('Stoke_Quality', models.CharField()),
                ('Rating', models.FloatField()),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
